// Auto-generated by scripts/generate-vercel-env.mjs during production builds.
// Do not edit deployed values here; set Vercel Environment Variables instead.
export const environment = {
  "production": true,
  "apiBaseUrl": "https://api.graceops.de/api",
  "keycloak": {
    "url": "https://auth.graceops.de",
    "realm": "hanmaum-dn-prod",
    "clientId": "hanmaum-dashboard"
  }
};
